version: '3.4'

services:
  tasklist:
    image: ${DOCKER_REGISTRY}tasklist
    build:
      context: .
      dockerfile: TaskList/Dockerfile
    depends_on: 
      - tasklist-db
    environment:
      - ConnectionStrings__DefaultConnection=host=tasklist-db;database=tasks;password=P@ssw0rd;username=postgres

  tasklist-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - ACCEPT_EULA=Y
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=tasks