kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-mssql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-tasks-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
      matchLabels:
        app: tasks-app
  template:
    metadata:
      labels:
        app: tasks-app
    spec:
      containers:
      - image: hossambarakat/tasklist
        imagePullPolicy: IfNotPresent
        name: tasks-app
        ports:
        - containerPort: 80
          name: tasks-app
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Server={{ .Release.Name }}-mssql-service;Database=Tasks;uid=sa;pwd=P@ssw0rd;MultipleActiveResultSets=true"
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-tasks-app-svc
spec:
  selector:
    app: tasks-app
  type: LoadBalancer
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-mssql-deployment
spec:
  replicas: 1
  selector:
      matchLabels:
        app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: microsoft/mssql-server-linux
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "P@ssw0rd"
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mssql-data
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-mssql-service
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: NodePort