kind: Pod
apiVersion: v1
metadata:
  name: tasks-app
spec:
  containers:
  - name: tasks-app
    image: hossambarakat/tasklist-postgres
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80