kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tasklist-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tasks-app-deployment
spec:
  replicas: 3
  selector:
      matchLabels:
        app: tasks-app
  template:
    metadata:
      labels:
        app: tasks-app
    spec:
      containers:
      - image: hossambarakat/tasklist-postgres
        imagePullPolicy: IfNotPresent
        name: tasks-app
        ports:
        - containerPort: 80
          name: tasks-app
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "host=tasklist-db-service;database=tasks;password=P@ssw0rd;username=postgres"
---
kind: Service
apiVersion: v1
metadata:
  name: tasks-app-svc
spec:
  selector:
    app: tasks-app
  type: LoadBalancer
  ports:
  - port: 8099
    targetPort: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tasklist-db-deployment
spec:
  replicas: 1
  selector:
      matchLabels:
        app: tasklist-db
  template:
    metadata:
      labels:
        app: tasklist-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: tasklist-db
        image: postgres
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: POSTGRES_PASSWORD
          value: "P@ssw0rd"
        - name: POSTGRES_DB
          value: "tasks"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: tasklist-db
          mountPath: /var/lib/postgresql/data/pgdata
      volumes:
      - name: tasklist-db
        persistentVolumeClaim:
          claimName: tasklist-postgres-data
---
kind: Service
apiVersion: v1
metadata:
  name: tasklist-db-service
spec:
  selector:
    app: tasklist-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer